#!/bin/bash -e

# Function to run commands in the chroot environment
run_in_chroot() {
  echo "Running in chroot: $1"
  on_chroot << EOF
$1
EOF
}

# Function to check and update config files
update_config_file() {
  local file=$1
  local pattern=$2
  local entry=$3
  echo "Updating $file: Adding $entry"
  if grep -q "$pattern" "$file"; then
    echo "Seems $pattern parameter already set in $file, skipping."
  else
    echo "$entry" >> "$file"
  fi
}


# Default paths
CONFIG_PATH="${ROOTFS_DIR}/boot/config.txt"
CMDLINE_PATH="${ROOTFS_DIR}/boot/cmdline.txt"


# Update paths if the files contain "DO NOT EDIT THIS FILE"
echo "Checking for 'DO NOT EDIT THIS FILE' in config.txt and cmdline.txt"
for file in config.txt cmdline.txt; do
  if grep -q 'DO NOT EDIT THIS FILE' "${ROOTFS_DIR}/boot/$file"; then
    eval "${file^^}_PATH=\"${ROOTFS_DIR}/boot/firmware/$file\""
  fi
done

# Set Debian frontend to Noninteractive
echo "Setting Debian frontend to Noninteractive"
run_in_chroot "
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
export DEBIAN_FRONTEND=noninteractive
"

# Update CA certificates for a secure connection to GitHub
echo "Update CA certificates for a secure connection to GitHub"
run_in_chroot "update-ca-certificates --fresh"

# Download and set up tnn-beta
echo "Cloning tnn repository"
if [ ! -d "${ROOTFS_DIR}/home/${FIRST_USER_NAME}/tnn-beta" ]; then
  run_in_chroot "
  git clone https://github.com/PE1FTL/tnn179cb55beta.git /home/${FIRST_USER_NAME}/tnn-beta
  chmod -R 775 /home/${FIRST_USER_NAME}/tnn-beta
  chown -R pi:pi /home/${FIRST_USER_NAME}/tnn-beta
  "
else
  echo "tnn repository already exists, skipping clone."
fi

# compile tnn-beta
echo "compile tnn-beta"
run_in_chroot "
cd /home/${FIRST_USER_NAME}/tnn-beta
make baseinstall
"

